---
title: "PC Variance Explained"
author: "Alexander Bergendorf"
date: "2023-10-30"
output: html_document
---

# Library Import

```{r}
library(Seurat)
library(mixOmics)
library(tidyverse)
library(orthogene)
library(dittoSeq)
library(openxlsx)
library(ggrepel)
home_dir <- "C:/Users/aberg/OneDrive/Desktop/Research_Brubaker/Undergraduate Research/AD TransComp-R Project Summer-Fall 2023/Brubaker Summer Research 2023"
#home_dir <- "C:/Users/Alexander/OneDrive/Desktop/Research_Brubaker/Undergraduate Research/AD TransComp-R Project Summer-Fall 2023/Brubaker Summer Research 2023"
```

# sPCA (GSE175814)

```{r}
# Loading mouse object with spca loadings
mouse_spca <- readRDS(file = paste0(home_dir, "/AD_mouse_objects_ortholog/mouse_spca_loadings_merged_500.RData"))

# Loading human object with spca projections
human <- readRDS(file = paste0(home_dir, "/sc_human_objects/gse175814_microglia_final.RData"))
```


```{r}
# Getting mouse loadings
mouse_loading_f <- data.frame(mouse_spca@reductions$spca@feature.loadings)

# Getting human gene expression matrix
t_filt_human_ex <- data.frame(human@assays$RNA$scale.data)
```

```{r}
# Loading pre-computed 1:1 ortholog matrix (replaces convert_orthologs() call)
# Row names = human gene symbols, input_gene column = mouse ortholog
ortholog_mat <- read.csv(paste0(home_dir, "/ortholog_matrix_IMPORTANT_6datasets.csv"),
                         row.names = 1,
                         stringsAsFactors = FALSE)

# Restrict to orthologs whose human symbol is present in the human expression matrix
# (mirrors the implicit filter convert_orthologs applied to row.names(t_filt_human_ex))
ortholog_mat <- ortholog_mat %>%
  filter(row.names(ortholog_mat) %in% row.names(t_filt_human_ex))

# Filter orthologs to those whose mouse symbol is in the mouse loadings
ortholog_mat <- ortholog_mat %>%
  filter(input_gene %in% row.names(mouse_loading_f))

# Filter human expression matrix on HUMAN symbols (== row.names(ortholog_mat))
t_filt_human_ex <- t_filt_human_ex %>%
  filter(row.names(t_filt_human_ex) %in% row.names(ortholog_mat))

# Align ordering so row i of t_filt_human_ex corresponds to row i of ortholog_mat
ortholog_mat    <- ortholog_mat[order(row.names(ortholog_mat)), , drop = FALSE]
t_filt_human_ex <- t_filt_human_ex[order(row.names(t_filt_human_ex)), , drop = FALSE]

# Sanity check before renaming human rows to mouse symbols
stopifnot(all(row.names(t_filt_human_ex) == row.names(ortholog_mat)))

# Rename human expression rows to mouse symbols
row.names(t_filt_human_ex) <- ortholog_mat$input_gene

# Filter mouse_loading_f to only keep mouse genes present in ortholog_mat (final intersection)
mouse_loading_f <- mouse_loading_f %>%
  filter(row.names(mouse_loading_f) %in% ortholog_mat$input_gene)

# Arrange both alphabetically by mouse symbols
mouse_loading_f <- mouse_loading_f %>% arrange(row.names(mouse_loading_f))
t_filt_human_ex <- t_filt_human_ex %>% arrange(row.names(t_filt_human_ex))

# Sanity check - should be TRUE / equal
stopifnot(all(row.names(mouse_loading_f) == row.names(t_filt_human_ex)))
cat("Number of matched genes:", nrow(mouse_loading_f), "\n")
```


```{r}
t_filt_human_ex <- t(t_filt_human_ex)
t_filt_human_ex <- as.matrix(t_filt_human_ex)
mouse_loading_f <- as.matrix(mouse_loading_f)
ncol(mouse_loading_f)
```


```{r}
# Get the variance of the spca projections
var_mh <- lapply(1:ncol(mouse_loading_f), function(x) (t(mouse_loading_f[,x])%*%t(t_filt_human_ex)%*%t_filt_human_ex%*%mouse_loading_f[,x])/(sum(diag(t(mouse_loading_f)%*%t(t_filt_human_ex)%*%t_filt_human_ex%*%mouse_loading_f))))
```



```{r}
variance_vec <- data.frame(variance = unlist(var_mh))
names_vec <- colnames(mouse_spca@reductions$spca@feature.loadings)
variance_vec$principal_component <- names_vec
write.csv(variance_vec, file = paste0(home_dir, "/spca_variances_gse175814.csv"))
variance_vec <- read.csv(file = paste0(home_dir, "/spca_variances_gse175814.csv"))
variance_vec$cum_var <- cumsum(variance_vec$variance)
variance_vec <- variance_vec %>%
  mutate(observation = row_number())
variance_vec
```

```{r}
variance_vec_human <- read.csv(file = paste0(home_dir, "/spca_variances_gse175814.csv"), row.names = 1)
variance_vec_human$cum_var <- cumsum(variance_vec_human$variance)
variance_vec_human$observation <- 1:nrow(variance_vec_human) 
variance_vec_human

variance_vec_mouse <- read.csv(paste0(home_dir, "/spca_variances_mouse_merged.csv"))
colnames(variance_vec_mouse) <- c("sPC", "sdev")
variance_vec_mouse$cum_var <- cumsum(variance_vec_mouse$sdev)
variance_vec_mouse$variance <- variance_vec_mouse$sdev / sum(variance_vec_mouse$sdev)
variance_vec_mouse$observation <- 1:nrow(variance_vec_mouse) 
variance_vec_mouse


new_df <- data.frame(principal_components = variance_vec_human$principal_component,
                     human_var = variance_vec_human$variance,
                     mouse_var = variance_vec_mouse$variance)


new_df <- new_df[order(-new_df$human_var), ]
top_5 <- head(new_df, 5)
new_df
write.csv(new_df, file = paste0(home_dir, "/merged_gse175814_var_spca.csv"))
```

```{r}
p <- ggplot(new_df, aes(x = 100 * mouse_var, y = 100 * human_var)) +  # Multiply both variables by 100
  geom_point(size = 3) +  # Increase dot size
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "black") +  # Add diagonal dashed line
  scale_x_continuous(limits = c(0, 35), name = "Var Exp in Mouse (%)") +
  scale_y_continuous(limits = c(0, 35), name = "Var Exp in Human (%)") +
  theme_classic() + 
  theme_bw() +
  annotate("text", x = 100 * top_5$mouse_var, y = 100 * top_5$human_var, label = top_5$principal_components, hjust = -0.4, vjust = -0.4, size = 4)

ggsave(paste0(home_dir, "/figures/manuscript/gse175814_spca_cross_species_variances.pdf"), width = 6, height = 6) # name the file as an 
```


# PCA (GSE175814)

```{r}
# Loading mouse object with spca loadings
mouse_pca <- readRDS(file = paste0(home_dir, "/AD_mouse_objects_ortholog/mouse_pca_loadings_merged.RData"))

# Loading human object with spca projections
human <- readRDS(file = paste0(home_dir, "/sc_human_objects/gse175814_microglia_final.RData"))
```


```{r}
# Getting mouse loadings
mouse_loading_f <- data.frame(mouse_pca@reductions$pca@feature.loadings)

# Getting human gene expression matrix
t_filt_human_ex <- data.frame(human@assays$RNA$scale.data)
```

```{r}
# Loading pre-computed 1:1 ortholog matrix (replaces convert_orthologs() call)
# Row names = human gene symbols, input_gene column = mouse ortholog
ortholog_mat <- read.csv(paste0(home_dir, "/ortholog_matrix_IMPORTANT_6datasets.csv"),
                         row.names = 1,
                         stringsAsFactors = FALSE)

# Restrict to orthologs whose human symbol is present in the human expression matrix
# (mirrors the implicit filter convert_orthologs applied to row.names(t_filt_human_ex))
ortholog_mat <- ortholog_mat %>%
  filter(row.names(ortholog_mat) %in% row.names(t_filt_human_ex))

# Filter orthologs to those whose mouse symbol is in the mouse loadings
ortholog_mat <- ortholog_mat %>%
  filter(input_gene %in% row.names(mouse_loading_f))

# Filter human expression matrix on HUMAN symbols (== row.names(ortholog_mat))
t_filt_human_ex <- t_filt_human_ex %>%
  filter(row.names(t_filt_human_ex) %in% row.names(ortholog_mat))

# Align ordering so row i of t_filt_human_ex corresponds to row i of ortholog_mat
ortholog_mat    <- ortholog_mat[order(row.names(ortholog_mat)), , drop = FALSE]
t_filt_human_ex <- t_filt_human_ex[order(row.names(t_filt_human_ex)), , drop = FALSE]

# Sanity check before renaming human rows to mouse symbols
stopifnot(all(row.names(t_filt_human_ex) == row.names(ortholog_mat)))

# Rename human expression rows to mouse symbols
row.names(t_filt_human_ex) <- ortholog_mat$input_gene

# Filter mouse_loading_f to only keep mouse genes present in ortholog_mat (final intersection)
mouse_loading_f <- mouse_loading_f %>%
  filter(row.names(mouse_loading_f) %in% ortholog_mat$input_gene)

# Arrange both alphabetically by mouse symbols
mouse_loading_f <- mouse_loading_f %>% arrange(row.names(mouse_loading_f))
t_filt_human_ex <- t_filt_human_ex %>% arrange(row.names(t_filt_human_ex))

# Sanity check - should be TRUE / equal
stopifnot(all(row.names(mouse_loading_f) == row.names(t_filt_human_ex)))
cat("Number of matched genes:", nrow(mouse_loading_f), "\n")
```




```{r}
t_filt_human_ex <- t(t_filt_human_ex)
t_filt_human_ex <- as.matrix(t_filt_human_ex)
mouse_loading_f <- as.matrix(mouse_loading_f)
ncol(mouse_loading_f)
```




```{r}
# Calculate variances of human pca
var_mh <- lapply(1:ncol(mouse_loading_f), function(x) (t(mouse_loading_f[,x])%*%t(t_filt_human_ex)%*%t_filt_human_ex%*%mouse_loading_f[,x])/(sum(diag(t(mouse_loading_f)%*%t(t_filt_human_ex)%*%t_filt_human_ex%*%mouse_loading_f))))
```

```{r}
variance_vec <- data.frame(variance = unlist(var_mh))
names_vec <- colnames(mouse_pca@reductions$pca@feature.loadings)
variance_vec$principal_component <- names_vec
write.csv(variance_vec, file = paste0(home_dir, "/pca_variances_gse175814.csv"))
variance_vec <- read.csv(file = paste0(home_dir, "/pca_variances_gse175814.csv"))
variance_vec$cum_var <- cumsum(variance_vec$variance)
variance_vec <- variance_vec %>%
  mutate(observation = row_number())
variance_vec
```

```{r}
variance_vec_human <- read.csv(file = paste0(home_dir, "/pca_variances_gse175814.csv"), row.names = 1)
variance_vec_human$cum_var <- cumsum(variance_vec_human$variance)
variance_vec_human$observation <- 1:nrow(variance_vec_human) 
variance_vec_human

variance_vec_mouse <- read.csv(paste0(home_dir, "/pca_variances_mouse_merged.csv"))
colnames(variance_vec_mouse) <- c("sPC", "sdev")
variance_vec_mouse$cum_var <- cumsum(variance_vec_mouse$sdev)
variance_vec_mouse$variance <- variance_vec_mouse$sdev / sum(variance_vec_mouse$sdev)
variance_vec_mouse$observation <- 1:nrow(variance_vec_mouse) 
variance_vec_mouse


new_df <- data.frame(principal_components = variance_vec_human$principal_component,
                     human_var = variance_vec_human$variance,
                     mouse_var = variance_vec_mouse$variance)


new_df <- new_df[order(-new_df$human_var), ]
top_5 <- head(new_df, 5)
new_df
write.csv(new_df, file = paste0(home_dir, "/merged_gse175814_var_pca.csv"))
```

```{r}
p <- ggplot(new_df, aes(x = 100 * mouse_var, y = 100 * human_var)) +  
  geom_point(size = 3) +  
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "black") +  
  scale_x_continuous(limits = c(0, 27.5), name = "Var Exp in Mouse (%)") +
  scale_y_continuous(limits = c(0, 27.5), name = "Var Exp in Human (%)") +
  theme_classic() + 
  theme_bw() +
  annotate("text", x = 100 * top_5$mouse_var, y = 100 * top_5$human_var, label = top_5$principal_components, 
           hjust = -0.4, vjust = -0.4, size = 4)
ggsave(paste0(home_dir, "/figures/manuscript/gse175814_pca_cross_species_variances.pdf"), width = 6, height = 6)
```

# sPCA (GSE147528)

```{r}
# Loading mouse object with spca loadings
mouse_spca <- readRDS(file = paste0(home_dir, "/AD_mouse_objects_ortholog/mouse_spca_loadings_merged_500.RData"))

# Loading human object with spca projections
human <- readRDS(file = paste0(home_dir, "/sc_human_objects/gse147528_microglia_final.RData"))
```


```{r}
# Getting mouse loadings
mouse_loading_f <- data.frame(mouse_spca@reductions$spca@feature.loadings)

# Getting human gene expression matrix
t_filt_human_ex <- data.frame(human@assays$RNA$scale.data)
```

```{r}
# Loading pre-computed 1:1 ortholog matrix (replaces convert_orthologs() call)
# Row names = human gene symbols, input_gene column = mouse ortholog
ortholog_mat <- read.csv(paste0(home_dir, "/ortholog_matrix_IMPORTANT_6datasets.csv"),
                         row.names = 1,
                         stringsAsFactors = FALSE)

# Restrict to orthologs whose human symbol is present in the human expression matrix
# (mirrors the implicit filter convert_orthologs applied to row.names(t_filt_human_ex))
ortholog_mat <- ortholog_mat %>%
  filter(row.names(ortholog_mat) %in% row.names(t_filt_human_ex))

# Filter orthologs to those whose mouse symbol is in the mouse loadings
ortholog_mat <- ortholog_mat %>%
  filter(input_gene %in% row.names(mouse_loading_f))

# Filter human expression matrix on HUMAN symbols (== row.names(ortholog_mat))
t_filt_human_ex <- t_filt_human_ex %>%
  filter(row.names(t_filt_human_ex) %in% row.names(ortholog_mat))

# Align ordering so row i of t_filt_human_ex corresponds to row i of ortholog_mat
ortholog_mat    <- ortholog_mat[order(row.names(ortholog_mat)), , drop = FALSE]
t_filt_human_ex <- t_filt_human_ex[order(row.names(t_filt_human_ex)), , drop = FALSE]

# Sanity check before renaming human rows to mouse symbols
stopifnot(all(row.names(t_filt_human_ex) == row.names(ortholog_mat)))

# Rename human expression rows to mouse symbols
row.names(t_filt_human_ex) <- ortholog_mat$input_gene

# Filter mouse_loading_f to only keep mouse genes present in ortholog_mat (final intersection)
mouse_loading_f <- mouse_loading_f %>%
  filter(row.names(mouse_loading_f) %in% ortholog_mat$input_gene)

# Arrange both alphabetically by mouse symbols
mouse_loading_f <- mouse_loading_f %>% arrange(row.names(mouse_loading_f))
t_filt_human_ex <- t_filt_human_ex %>% arrange(row.names(t_filt_human_ex))

# Sanity check - should be TRUE / equal
stopifnot(all(row.names(mouse_loading_f) == row.names(t_filt_human_ex)))
cat("Number of matched genes:", nrow(mouse_loading_f), "\n")
```


```{r}
t_filt_human_ex <- t(t_filt_human_ex)
t_filt_human_ex <- as.matrix(t_filt_human_ex)
mouse_loading_f <- as.matrix(mouse_loading_f)
ncol(mouse_loading_f)
```


```{r}
# Get the variance of the spca projections
var_mh <- lapply(1:ncol(mouse_loading_f), function(x) (t(mouse_loading_f[,x])%*%t(t_filt_human_ex)%*%t_filt_human_ex%*%mouse_loading_f[,x])/(sum(diag(t(mouse_loading_f)%*%t(t_filt_human_ex)%*%t_filt_human_ex%*%mouse_loading_f))))
```



```{r}
variance_vec <- data.frame(variance = unlist(var_mh))
names_vec <- colnames(mouse_spca@reductions$spca@feature.loadings)
variance_vec$principal_component <- names_vec
write.csv(variance_vec, file = paste0(home_dir, "/spca_variances_gse147528.csv"))
variance_vec <- read.csv(file = paste0(home_dir, "/spca_variances_gse147528.csv"))
variance_vec$cum_var <- cumsum(variance_vec$variance)
variance_vec <- variance_vec %>%
  mutate(observation = row_number())
variance_vec
```

```{r}
variance_vec_human <- read.csv(file = paste0(home_dir, "/spca_variances_gse147528.csv"), row.names = 1)
variance_vec_human$cum_var <- cumsum(variance_vec_human$variance)
variance_vec_human$observation <- 1:nrow(variance_vec_human) 
variance_vec_human

variance_vec_mouse <- read.csv(paste0(home_dir, "/spca_variances_mouse_merged.csv"))
colnames(variance_vec_mouse) <- c("sPC", "sdev")
variance_vec_mouse$cum_var <- cumsum(variance_vec_mouse$sdev)
variance_vec_mouse$variance <- variance_vec_mouse$sdev / sum(variance_vec_mouse$sdev)
variance_vec_mouse$observation <- 1:nrow(variance_vec_mouse) 
variance_vec_mouse


new_df <- data.frame(principal_components = variance_vec_human$principal_component,
                     human_var = variance_vec_human$variance,
                     mouse_var = variance_vec_mouse$variance)


new_df <- new_df[order(-new_df$human_var), ]
top_5 <- head(new_df, 5)
new_df
write.csv(new_df, file = paste0(home_dir, "/merged_gse147528_var_spca.csv"))
```

```{r}
p <- ggplot(new_df, aes(x = 100 * mouse_var, y = 100 * human_var)) +  # Multiply both variables by 100
  geom_point(size = 3) +  # Increase dot size
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "black") +  # Add diagonal dashed line
  scale_x_continuous(limits = c(0, 35), name = "Var Exp in Mouse (%)") +
  scale_y_continuous(limits = c(0, 35), name = "Var Exp in Human (%)") +
  theme_classic() + 
  theme_bw() +
  annotate("text", x = 100 * top_5$mouse_var, y = 100 * top_5$human_var, label = top_5$principal_components, hjust = -0.4, vjust = -0.4, size = 4)

ggsave(paste0(home_dir, "/figures/manuscript/gse147528_spca_cross_species_variances.pdf"), width = 6, height = 6) # name the file as an 
```


# PCA (GSE147528)

```{r}
# Loading mouse object with spca loadings
mouse_pca <- readRDS(file = paste0(home_dir, "/AD_mouse_objects_ortholog/mouse_pca_loadings_merged.RData"))

# Loading human object with spca projections
human <- readRDS(file = paste0(home_dir, "/sc_human_objects/gse147528_microglia_final.RData"))
```


```{r}
# Getting mouse loadings
mouse_loading_f <- data.frame(mouse_pca@reductions$pca@feature.loadings)

# Getting human gene expression matrix
t_filt_human_ex <- data.frame(human@assays$RNA$scale.data)
```


```{r}
# Loading pre-computed 1:1 ortholog matrix (replaces convert_orthologs() call)
# Row names = human gene symbols, input_gene column = mouse ortholog
ortholog_mat <- read.csv(paste0(home_dir, "/ortholog_matrix_IMPORTANT_6datasets.csv"),
                         row.names = 1,
                         stringsAsFactors = FALSE)

# Restrict to orthologs whose human symbol is present in the human expression matrix
# (mirrors the implicit filter convert_orthologs applied to row.names(t_filt_human_ex))
ortholog_mat <- ortholog_mat %>%
  filter(row.names(ortholog_mat) %in% row.names(t_filt_human_ex))

# Filter orthologs to those whose mouse symbol is in the mouse loadings
ortholog_mat <- ortholog_mat %>%
  filter(input_gene %in% row.names(mouse_loading_f))

# Filter human expression matrix on HUMAN symbols (== row.names(ortholog_mat))
t_filt_human_ex <- t_filt_human_ex %>%
  filter(row.names(t_filt_human_ex) %in% row.names(ortholog_mat))

# Align ordering so row i of t_filt_human_ex corresponds to row i of ortholog_mat
ortholog_mat    <- ortholog_mat[order(row.names(ortholog_mat)), , drop = FALSE]
t_filt_human_ex <- t_filt_human_ex[order(row.names(t_filt_human_ex)), , drop = FALSE]

# Sanity check before renaming human rows to mouse symbols
stopifnot(all(row.names(t_filt_human_ex) == row.names(ortholog_mat)))

# Rename human expression rows to mouse symbols
row.names(t_filt_human_ex) <- ortholog_mat$input_gene

# Filter mouse_loading_f to only keep mouse genes present in ortholog_mat (final intersection)
mouse_loading_f <- mouse_loading_f %>%
  filter(row.names(mouse_loading_f) %in% ortholog_mat$input_gene)

# Arrange both alphabetically by mouse symbols
mouse_loading_f <- mouse_loading_f %>% arrange(row.names(mouse_loading_f))
t_filt_human_ex <- t_filt_human_ex %>% arrange(row.names(t_filt_human_ex))

# Sanity check - should be TRUE / equal
stopifnot(all(row.names(mouse_loading_f) == row.names(t_filt_human_ex)))
cat("Number of matched genes:", nrow(mouse_loading_f), "\n")
```


```{r}
t_filt_human_ex <- t(t_filt_human_ex)
t_filt_human_ex <- as.matrix(t_filt_human_ex)
mouse_loading_f <- as.matrix(mouse_loading_f)
ncol(mouse_loading_f)
```


```{r}
# Calculate variances of human pca
var_mh <- lapply(1:ncol(mouse_loading_f), function(x) (t(mouse_loading_f[,x])%*%t(t_filt_human_ex)%*%t_filt_human_ex%*%mouse_loading_f[,x])/(sum(diag(t(mouse_loading_f)%*%t(t_filt_human_ex)%*%t_filt_human_ex%*%mouse_loading_f))))
```

```{r}
variance_vec <- data.frame(variance = unlist(var_mh))
names_vec <- colnames(mouse_pca@reductions$pca@feature.loadings)
variance_vec$principal_component <- names_vec
write.csv(variance_vec, file = paste0(home_dir, "/pca_variances_gse147528.csv"))
variance_vec <- read.csv(file = paste0(home_dir, "/pca_variances_gse147528.csv"))
variance_vec$cum_var <- cumsum(variance_vec$variance)
variance_vec <- variance_vec %>%
  mutate(observation = row_number())
variance_vec
```

```{r}
variance_vec_human <- read.csv(file = paste0(home_dir, "/pca_variances_gse147528.csv"), row.names = 1)
variance_vec_human$cum_var <- cumsum(variance_vec_human$variance)
variance_vec_human$observation <- 1:nrow(variance_vec_human) 
variance_vec_human

variance_vec_mouse <- read.csv(paste0(home_dir, "/pca_variances_mouse_merged.csv"))
colnames(variance_vec_mouse) <- c("sPC", "sdev")
variance_vec_mouse$cum_var <- cumsum(variance_vec_mouse$sdev)
variance_vec_mouse$variance <- variance_vec_mouse$sdev / sum(variance_vec_mouse$sdev)
variance_vec_mouse$observation <- 1:nrow(variance_vec_mouse) 
variance_vec_mouse


new_df <- data.frame(principal_components = variance_vec_human$principal_component,
                     human_var = variance_vec_human$variance,
                     mouse_var = variance_vec_mouse$variance)


new_df <- new_df[order(-new_df$human_var), ]
top_5 <- head(new_df, 6)
new_df
write.csv(new_df, file = paste0(home_dir, "/merged_gse147528_var_pca.csv"))
```

```{r}
p <- ggplot(new_df, aes(x = 100 * mouse_var, y = 100 * human_var)) +  
  geom_point(size = 3) +  
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "black") +  
  scale_x_continuous(limits = c(0, 27.5), name = "Var Exp in Mouse (%)") +
  scale_y_continuous(limits = c(0, 27.5), name = "Var Exp in Human (%)") +
  theme_classic() + 
  theme_bw() +
  annotate("text", x = 100 * top_5$mouse_var, y = 100 * top_5$human_var, label = top_5$principal_components, 
           hjust = -0.4, vjust = -0.4, size = 4)

ggsave(paste0(home_dir, "/figures/manuscript/gse147528_pca_cross_species_variances.pdf"), width = 6, height = 6) # name the file as an
```

# sPCA (GSE174367)

```{r}
# Loading mouse object with spca loadings
mouse_spca <- readRDS(file = paste0(home_dir, "/AD_mouse_objects_ortholog/mouse_spca_loadings_merged_500.RData"))

# Loading human object with spca projections
human <- readRDS(file = paste0(home_dir, "/sc_human_objects/gse174367_microglia_final.RData"))
```


```{r}
# Getting mouse loadings
mouse_loading_f <- data.frame(mouse_spca@reductions$spca@feature.loadings)

# Getting human gene expression matrix
t_filt_human_ex <- data.frame(human@assays$RNA$scale.data)
```

```{r}
# Loading pre-computed 1:1 ortholog matrix (replaces convert_orthologs() call)
# Row names = human gene symbols, input_gene column = mouse ortholog
ortholog_mat <- read.csv(paste0(home_dir, "/ortholog_matrix_IMPORTANT_6datasets.csv"),
                         row.names = 1,
                         stringsAsFactors = FALSE)

# Restrict to orthologs whose human symbol is present in the human expression matrix
# (mirrors the implicit filter convert_orthologs applied to row.names(t_filt_human_ex))
ortholog_mat <- ortholog_mat %>%
  filter(row.names(ortholog_mat) %in% row.names(t_filt_human_ex))

# Filter orthologs to those whose mouse symbol is in the mouse loadings
ortholog_mat <- ortholog_mat %>%
  filter(input_gene %in% row.names(mouse_loading_f))

# Filter human expression matrix on HUMAN symbols (== row.names(ortholog_mat))
t_filt_human_ex <- t_filt_human_ex %>%
  filter(row.names(t_filt_human_ex) %in% row.names(ortholog_mat))

# Align ordering so row i of t_filt_human_ex corresponds to row i of ortholog_mat
ortholog_mat    <- ortholog_mat[order(row.names(ortholog_mat)), , drop = FALSE]
t_filt_human_ex <- t_filt_human_ex[order(row.names(t_filt_human_ex)), , drop = FALSE]

# Sanity check before renaming human rows to mouse symbols
stopifnot(all(row.names(t_filt_human_ex) == row.names(ortholog_mat)))

# Rename human expression rows to mouse symbols
row.names(t_filt_human_ex) <- ortholog_mat$input_gene

# Filter mouse_loading_f to only keep mouse genes present in ortholog_mat (final intersection)
mouse_loading_f <- mouse_loading_f %>%
  filter(row.names(mouse_loading_f) %in% ortholog_mat$input_gene)

# Arrange both alphabetically by mouse symbols
mouse_loading_f <- mouse_loading_f %>% arrange(row.names(mouse_loading_f))
t_filt_human_ex <- t_filt_human_ex %>% arrange(row.names(t_filt_human_ex))

# Sanity check - should be TRUE / equal
stopifnot(all(row.names(mouse_loading_f) == row.names(t_filt_human_ex)))
cat("Number of matched genes:", nrow(mouse_loading_f), "\n")
```


```{r}
t_filt_human_ex <- t(t_filt_human_ex)
t_filt_human_ex <- as.matrix(t_filt_human_ex)
mouse_loading_f <- as.matrix(mouse_loading_f)
ncol(mouse_loading_f)
```


```{r}
# Get the variance of the spca projections
var_mh <- lapply(1:ncol(mouse_loading_f), function(x) (t(mouse_loading_f[,x])%*%t(t_filt_human_ex)%*%t_filt_human_ex%*%mouse_loading_f[,x])/(sum(diag(t(mouse_loading_f)%*%t(t_filt_human_ex)%*%t_filt_human_ex%*%mouse_loading_f))))
```



```{r}
variance_vec <- data.frame(variance = unlist(var_mh))
names_vec <- colnames(mouse_spca@reductions$spca@feature.loadings)
variance_vec$principal_component <- names_vec
write.csv(variance_vec, file = paste0(home_dir, "/spca_variances_gse174367.csv"))
variance_vec <- read.csv(file = paste0(home_dir, "/spca_variances_gse174367.csv"))
variance_vec$cum_var <- cumsum(variance_vec$variance)
variance_vec <- variance_vec %>%
  mutate(observation = row_number())
variance_vec
```

```{r}
variance_vec_human <- read.csv(file = paste0(home_dir, "/spca_variances_gse174367.csv"), row.names = 1)
variance_vec_human$cum_var <- cumsum(variance_vec_human$variance)
variance_vec_human$observation <- 1:nrow(variance_vec_human) 
variance_vec_human

variance_vec_mouse <- read.csv(paste0(home_dir, "/spca_variances_mouse_merged.csv"))
colnames(variance_vec_mouse) <- c("sPC", "sdev")
variance_vec_mouse$cum_var <- cumsum(variance_vec_mouse$sdev)
variance_vec_mouse$variance <- variance_vec_mouse$sdev / sum(variance_vec_mouse$sdev)
variance_vec_mouse$observation <- 1:nrow(variance_vec_mouse) 
variance_vec_mouse


new_df <- data.frame(principal_components = variance_vec_human$principal_component,
                     human_var = variance_vec_human$variance,
                     mouse_var = variance_vec_mouse$variance)


new_df <- new_df[order(-new_df$human_var), ]
top_5 <- head(new_df, 5)
new_df
write.csv(new_df, file = paste0(home_dir, "/merged_gse174367_var_spca.csv"))
```

```{r}
p <- ggplot(new_df, aes(x = 100 * mouse_var, y = 100 * human_var)) +  # Multiply both variables by 100
  geom_point(size = 3) +  # Increase dot size
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "black") +  # Add diagonal dashed line
  scale_x_continuous(limits = c(0, 35), name = "Var Exp in Mouse (%)") +
  scale_y_continuous(limits = c(0, 35), name = "Var Exp in Human (%)") +
  theme_classic() + 
  theme_bw() +
  annotate("text", x = 100 * top_5$mouse_var, y = 100 * top_5$human_var, label = top_5$principal_components, hjust = -0.4, vjust = -0.4, size = 4)

ggsave(paste0(home_dir, "/figures/manuscript/gse174367_spca_cross_species_variances.pdf"), width = 6, height = 6) # name the file as an 
```

# PCA (GSE174367)

```{r}
# Loading mouse object with spca loadings
mouse_pca <- readRDS(file = paste0(home_dir, "/AD_mouse_objects_ortholog/mouse_pca_loadings_merged.RData"))

# Loading human object with spca projections
human <- readRDS(file = paste0(home_dir, "/sc_human_objects/gse174367_microglia_final.RData"))
```


```{r}
# Getting mouse loadings
mouse_loading_f <- data.frame(mouse_pca@reductions$pca@feature.loadings)

# Getting human gene expression matrix
t_filt_human_ex <- data.frame(human@assays$RNA$scale.data)
```

```{r}
# Loading pre-computed 1:1 ortholog matrix (replaces convert_orthologs() call)
# Row names = human gene symbols, input_gene column = mouse ortholog
ortholog_mat <- read.csv(paste0(home_dir, "/ortholog_matrix_IMPORTANT_6datasets.csv"),
                         row.names = 1,
                         stringsAsFactors = FALSE)

# Restrict to orthologs whose human symbol is present in the human expression matrix
# (mirrors the implicit filter convert_orthologs applied to row.names(t_filt_human_ex))
ortholog_mat <- ortholog_mat %>%
  filter(row.names(ortholog_mat) %in% row.names(t_filt_human_ex))

# Filter orthologs to those whose mouse symbol is in the mouse loadings
ortholog_mat <- ortholog_mat %>%
  filter(input_gene %in% row.names(mouse_loading_f))

# Filter human expression matrix on HUMAN symbols (== row.names(ortholog_mat))
t_filt_human_ex <- t_filt_human_ex %>%
  filter(row.names(t_filt_human_ex) %in% row.names(ortholog_mat))

# Align ordering so row i of t_filt_human_ex corresponds to row i of ortholog_mat
ortholog_mat    <- ortholog_mat[order(row.names(ortholog_mat)), , drop = FALSE]
t_filt_human_ex <- t_filt_human_ex[order(row.names(t_filt_human_ex)), , drop = FALSE]

# Sanity check before renaming human rows to mouse symbols
stopifnot(all(row.names(t_filt_human_ex) == row.names(ortholog_mat)))

# Rename human expression rows to mouse symbols
row.names(t_filt_human_ex) <- ortholog_mat$input_gene

# Filter mouse_loading_f to only keep mouse genes present in ortholog_mat (final intersection)
mouse_loading_f <- mouse_loading_f %>%
  filter(row.names(mouse_loading_f) %in% ortholog_mat$input_gene)

# Arrange both alphabetically by mouse symbols
mouse_loading_f <- mouse_loading_f %>% arrange(row.names(mouse_loading_f))
t_filt_human_ex <- t_filt_human_ex %>% arrange(row.names(t_filt_human_ex))

# Sanity check - should be TRUE / equal
stopifnot(all(row.names(mouse_loading_f) == row.names(t_filt_human_ex)))
cat("Number of matched genes:", nrow(mouse_loading_f), "\n")
```




```{r}
t_filt_human_ex <- t(t_filt_human_ex)
t_filt_human_ex <- as.matrix(t_filt_human_ex)
mouse_loading_f <- as.matrix(mouse_loading_f)
ncol(mouse_loading_f)
```




```{r}
# Calculate variances of human pca
var_mh <- lapply(1:ncol(mouse_loading_f), function(x) (t(mouse_loading_f[,x])%*%t(t_filt_human_ex)%*%t_filt_human_ex%*%mouse_loading_f[,x])/(sum(diag(t(mouse_loading_f)%*%t(t_filt_human_ex)%*%t_filt_human_ex%*%mouse_loading_f))))
```

```{r}
variance_vec <- data.frame(variance = unlist(var_mh))
names_vec <- colnames(mouse_pca@reductions$pca@feature.loadings)
variance_vec$principal_component <- names_vec
write.csv(variance_vec, file = paste0(home_dir, "/pca_variances_gse174367.csv"))
variance_vec <- read.csv(file = paste0(home_dir, "/pca_variances_gse174367.csv"))
variance_vec$cum_var <- cumsum(variance_vec$variance)
variance_vec <- variance_vec %>%
  mutate(observation = row_number())
variance_vec
```

```{r}
variance_vec_human <- read.csv(file = paste0(home_dir, "/pca_variances_gse174367.csv"), row.names = 1)
variance_vec_human$cum_var <- cumsum(variance_vec_human$variance)
variance_vec_human$observation <- 1:nrow(variance_vec_human) 
variance_vec_human

variance_vec_mouse <- read.csv(paste0(home_dir, "/pca_variances_mouse_merged.csv"))
colnames(variance_vec_mouse) <- c("sPC", "sdev")
variance_vec_mouse$cum_var <- cumsum(variance_vec_mouse$sdev)
variance_vec_mouse$variance <- variance_vec_mouse$sdev / sum(variance_vec_mouse$sdev)
variance_vec_mouse$observation <- 1:nrow(variance_vec_mouse) 
variance_vec_mouse


new_df <- data.frame(principal_components = variance_vec_human$principal_component,
                     human_var = variance_vec_human$variance,
                     mouse_var = variance_vec_mouse$variance)


new_df <- new_df[order(-new_df$human_var), ]
top_5 <- head(new_df, 5)
new_df
write.csv(new_df, file = paste0(home_dir, "/merged_gse174367_var_pca.csv"))
```

```{r}
p <- ggplot(new_df, aes(x = 100 * mouse_var, y = 100 * human_var)) +  
  geom_point(size = 3) +  
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "black") +  
  scale_x_continuous(limits = c(0, 27.5), name = "Var Exp in Mouse (%)") +
  scale_y_continuous(limits = c(0, 27.5), name = "Var Exp in Human (%)") +
  theme_classic() + 
  theme_bw() +
  annotate("text", x = 100 * top_5$mouse_var, y = 100 * top_5$human_var, label = top_5$principal_components, 
           hjust = -0.4, vjust = -0.4, size = 4)
ggsave(paste0(home_dir, "/figures/manuscript/gse174367_pca_cross_species_variances.pdf"), width = 6, height = 6)
```

# sPCA (GSE157827)

```{r}
# Loading mouse object with spca loadings
mouse_spca <- readRDS(file = paste0(home_dir, "/AD_mouse_objects_ortholog/mouse_spca_loadings_merged_500.RData"))

# Loading human object with spca projections
human <- readRDS(file = paste0(home_dir, "/sc_human_objects/gse157827_microglia_final.RData"))
```


```{r}
# Getting mouse loadings
mouse_loading_f <- data.frame(mouse_spca@reductions$spca@feature.loadings)

# Getting human gene expression matrix
t_filt_human_ex <- data.frame(human@assays$RNA$scale.data)
```

```{r}
# Loading pre-computed 1:1 ortholog matrix (replaces convert_orthologs() call)
# Row names = human gene symbols, input_gene column = mouse ortholog
ortholog_mat <- read.csv(paste0(home_dir, "/ortholog_matrix_IMPORTANT_6datasets.csv"),
                         row.names = 1,
                         stringsAsFactors = FALSE)

# Restrict to orthologs whose human symbol is present in the human expression matrix
# (mirrors the implicit filter convert_orthologs applied to row.names(t_filt_human_ex))
ortholog_mat <- ortholog_mat %>%
  filter(row.names(ortholog_mat) %in% row.names(t_filt_human_ex))

# Filter orthologs to those whose mouse symbol is in the mouse loadings
ortholog_mat <- ortholog_mat %>%
  filter(input_gene %in% row.names(mouse_loading_f))

# Filter human expression matrix on HUMAN symbols (== row.names(ortholog_mat))
t_filt_human_ex <- t_filt_human_ex %>%
  filter(row.names(t_filt_human_ex) %in% row.names(ortholog_mat))

# Align ordering so row i of t_filt_human_ex corresponds to row i of ortholog_mat
ortholog_mat    <- ortholog_mat[order(row.names(ortholog_mat)), , drop = FALSE]
t_filt_human_ex <- t_filt_human_ex[order(row.names(t_filt_human_ex)), , drop = FALSE]

# Sanity check before renaming human rows to mouse symbols
stopifnot(all(row.names(t_filt_human_ex) == row.names(ortholog_mat)))

# Rename human expression rows to mouse symbols
row.names(t_filt_human_ex) <- ortholog_mat$input_gene

# Filter mouse_loading_f to only keep mouse genes present in ortholog_mat (final intersection)
mouse_loading_f <- mouse_loading_f %>%
  filter(row.names(mouse_loading_f) %in% ortholog_mat$input_gene)

# Arrange both alphabetically by mouse symbols
mouse_loading_f <- mouse_loading_f %>% arrange(row.names(mouse_loading_f))
t_filt_human_ex <- t_filt_human_ex %>% arrange(row.names(t_filt_human_ex))

# Sanity check - should be TRUE / equal
stopifnot(all(row.names(mouse_loading_f) == row.names(t_filt_human_ex)))
cat("Number of matched genes:", nrow(mouse_loading_f), "\n")
```


```{r}
t_filt_human_ex <- t(t_filt_human_ex)
t_filt_human_ex <- as.matrix(t_filt_human_ex)
mouse_loading_f <- as.matrix(mouse_loading_f)
ncol(mouse_loading_f)
```


```{r}
# Get the variance of the spca projections
var_mh <- lapply(1:ncol(mouse_loading_f), function(x) (t(mouse_loading_f[,x])%*%t(t_filt_human_ex)%*%t_filt_human_ex%*%mouse_loading_f[,x])/(sum(diag(t(mouse_loading_f)%*%t(t_filt_human_ex)%*%t_filt_human_ex%*%mouse_loading_f))))
```



```{r}
variance_vec <- data.frame(variance = unlist(var_mh))
names_vec <- colnames(mouse_spca@reductions$spca@feature.loadings)
variance_vec$principal_component <- names_vec
write.csv(variance_vec, file = paste0(home_dir, "/spca_variances_gse157827.csv"))
variance_vec <- read.csv(file = paste0(home_dir, "/spca_variances_gse157827.csv"))
variance_vec$cum_var <- cumsum(variance_vec$variance)
variance_vec <- variance_vec %>%
  mutate(observation = row_number())
variance_vec
```

```{r}
variance_vec_human <- read.csv(file = paste0(home_dir, "/spca_variances_gse157827.csv"), row.names = 1)
variance_vec_human$cum_var <- cumsum(variance_vec_human$variance)
variance_vec_human$observation <- 1:nrow(variance_vec_human) 
variance_vec_human

variance_vec_mouse <- read.csv(paste0(home_dir, "/spca_variances_mouse_merged.csv"))
colnames(variance_vec_mouse) <- c("sPC", "sdev")
variance_vec_mouse$cum_var <- cumsum(variance_vec_mouse$sdev)
variance_vec_mouse$variance <- variance_vec_mouse$sdev / sum(variance_vec_mouse$sdev)
variance_vec_mouse$observation <- 1:nrow(variance_vec_mouse) 
variance_vec_mouse


new_df <- data.frame(principal_components = variance_vec_human$principal_component,
                     human_var = variance_vec_human$variance,
                     mouse_var = variance_vec_mouse$variance)


new_df <- new_df[order(-new_df$human_var), ]
top_5 <- head(new_df, 5)
new_df
write.csv(new_df, file = paste0(home_dir, "/merged_gse157827_var_spca.csv"))
```

```{r}
p <- ggplot(new_df, aes(x = 100 * mouse_var, y = 100 * human_var)) +  # Multiply both variables by 100
  geom_point(size = 3) +  # Increase dot size
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "black") +  # Add diagonal dashed line
  scale_x_continuous(limits = c(0, 35), name = "Var Exp in Mouse (%)") +
  scale_y_continuous(limits = c(0, 35), name = "Var Exp in Human (%)") +
  theme_classic() + 
  theme_bw() +
  annotate("text", x = 100 * top_5$mouse_var, y = 100 * top_5$human_var, label = top_5$principal_components, hjust = -0.4, vjust = -0.4, size = 4)

ggsave(paste0(home_dir, "/figures/manuscript/gse157827_spca_cross_species_variances.pdf"), width = 6, height = 6) # name the file as an 
```

# PCA (GSE157827)

```{r}
# Loading mouse object with spca loadings
mouse_pca <- readRDS(file = paste0(home_dir, "/AD_mouse_objects_ortholog/mouse_pca_loadings_merged.RData"))

# Loading human object with spca projections
human <- readRDS(file = paste0(home_dir, "/sc_human_objects/gse157827_microglia_final.RData"))
```


```{r}
# Getting mouse loadings
mouse_loading_f <- data.frame(mouse_pca@reductions$pca@feature.loadings)

# Getting human gene expression matrix
t_filt_human_ex <- data.frame(human@assays$RNA$scale.data)
```

```{r}
# Loading pre-computed 1:1 ortholog matrix (replaces convert_orthologs() call)
# Row names = human gene symbols, input_gene column = mouse ortholog
ortholog_mat <- read.csv(paste0(home_dir, "/ortholog_matrix_IMPORTANT_6datasets.csv"),
                         row.names = 1,
                         stringsAsFactors = FALSE)

# Restrict to orthologs whose human symbol is present in the human expression matrix
# (mirrors the implicit filter convert_orthologs applied to row.names(t_filt_human_ex))
ortholog_mat <- ortholog_mat %>%
  filter(row.names(ortholog_mat) %in% row.names(t_filt_human_ex))

# Filter orthologs to those whose mouse symbol is in the mouse loadings
ortholog_mat <- ortholog_mat %>%
  filter(input_gene %in% row.names(mouse_loading_f))

# Filter human expression matrix on HUMAN symbols (== row.names(ortholog_mat))
t_filt_human_ex <- t_filt_human_ex %>%
  filter(row.names(t_filt_human_ex) %in% row.names(ortholog_mat))

# Align ordering so row i of t_filt_human_ex corresponds to row i of ortholog_mat
ortholog_mat    <- ortholog_mat[order(row.names(ortholog_mat)), , drop = FALSE]
t_filt_human_ex <- t_filt_human_ex[order(row.names(t_filt_human_ex)), , drop = FALSE]

# Sanity check before renaming human rows to mouse symbols
stopifnot(all(row.names(t_filt_human_ex) == row.names(ortholog_mat)))

# Rename human expression rows to mouse symbols
row.names(t_filt_human_ex) <- ortholog_mat$input_gene

# Filter mouse_loading_f to only keep mouse genes present in ortholog_mat (final intersection)
mouse_loading_f <- mouse_loading_f %>%
  filter(row.names(mouse_loading_f) %in% ortholog_mat$input_gene)

# Arrange both alphabetically by mouse symbols
mouse_loading_f <- mouse_loading_f %>% arrange(row.names(mouse_loading_f))
t_filt_human_ex <- t_filt_human_ex %>% arrange(row.names(t_filt_human_ex))

# Sanity check - should be TRUE / equal
stopifnot(all(row.names(mouse_loading_f) == row.names(t_filt_human_ex)))
cat("Number of matched genes:", nrow(mouse_loading_f), "\n")
```




```{r}
t_filt_human_ex <- t(t_filt_human_ex)
t_filt_human_ex <- as.matrix(t_filt_human_ex)
mouse_loading_f <- as.matrix(mouse_loading_f)
ncol(mouse_loading_f)
```




```{r}
# Calculate variances of human pca
var_mh <- lapply(1:ncol(mouse_loading_f), function(x) (t(mouse_loading_f[,x])%*%t(t_filt_human_ex)%*%t_filt_human_ex%*%mouse_loading_f[,x])/(sum(diag(t(mouse_loading_f)%*%t(t_filt_human_ex)%*%t_filt_human_ex%*%mouse_loading_f))))
```

```{r}
variance_vec <- data.frame(variance = unlist(var_mh))
names_vec <- colnames(mouse_pca@reductions$pca@feature.loadings)
variance_vec$principal_component <- names_vec
write.csv(variance_vec, file = paste0(home_dir, "/pca_variances_gse157827.csv"))
variance_vec <- read.csv(file = paste0(home_dir, "/pca_variances_gse157827.csv"))
variance_vec$cum_var <- cumsum(variance_vec$variance)
variance_vec <- variance_vec %>%
  mutate(observation = row_number())
variance_vec
```

```{r}
variance_vec_human <- read.csv(file = paste0(home_dir, "/pca_variances_gse157827.csv"), row.names = 1)
variance_vec_human$cum_var <- cumsum(variance_vec_human$variance)
variance_vec_human$observation <- 1:nrow(variance_vec_human) 
variance_vec_human

variance_vec_mouse <- read.csv(paste0(home_dir, "/pca_variances_mouse_merged.csv"))
colnames(variance_vec_mouse) <- c("sPC", "sdev")
variance_vec_mouse$cum_var <- cumsum(variance_vec_mouse$sdev)
variance_vec_mouse$variance <- variance_vec_mouse$sdev / sum(variance_vec_mouse$sdev)
variance_vec_mouse$observation <- 1:nrow(variance_vec_mouse) 
variance_vec_mouse


new_df <- data.frame(principal_components = variance_vec_human$principal_component,
                     human_var = variance_vec_human$variance,
                     mouse_var = variance_vec_mouse$variance)


new_df <- new_df[order(-new_df$human_var), ]
top_5 <- head(new_df, 5)
new_df
write.csv(new_df, file = paste0(home_dir, "/merged_gse157827_var_pca.csv"))
```

```{r}
p <- ggplot(new_df, aes(x = 100 * mouse_var, y = 100 * human_var)) +  
  geom_point(size = 3) +  
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "black") +  
  scale_x_continuous(limits = c(0, 27.5), name = "Var Exp in Mouse (%)") +
  scale_y_continuous(limits = c(0, 27.5), name = "Var Exp in Human (%)") +
  theme_classic() + 
  theme_bw() +
  annotate("text", x = 100 * top_5$mouse_var, y = 100 * top_5$human_var, label = top_5$principal_components, 
           hjust = -0.4, vjust = -0.4, size = 4)
ggsave(paste0(home_dir, "/figures/manuscript/gse157827_pca_cross_species_variances.pdf"), width = 6, height = 6)
```

# Session Info

```{r}
sessionInfo()
```

